### ISSUE TITLE
Please clarify: this plugin uploads all images into your cloudservice at octoprint.printpal.io, correct?

### ISSUE THREAD

**Issue by hn3000** [printpal-io/OctoPrint-BedCheckAI#2]
Hi,

I discovered your plugin through the octoprint plugin registry and the description does not mention that my images are uploaded to the cloud.

A quick look through your code shows that you in fact do upload photos to octoprint.printpal.io (here https://github.com/printpal-io/OctoPrint-BedCheckAI/blob/0ee8e88a3c7f1668fcb72857cc66733a3ffd3565/octoprint_bedcheckai/utils.py#L35 ) -- it would be nice if your description was more upfront about this. Specifically, in the section "How does it work?" this aspect should be mentioned. 

You should also make sure it's mentioned in your privacy policy.

Or do you also offer the ability to self-host your models?

**Comment by printpal-io** [comment]
> Hi,
> 
> I discovered your plugin through the octoprint plugin registry and the description does not mention that my images are uploaded to the cloud.
> 
> A quick look through your code shows that you in fact do upload photos to octoprint.printpal.io (here
> 
> https://github.com/printpal-io/OctoPrint-BedCheckAI/blob/0ee8e88a3c7f1668fcb72857cc66733a3ffd3565/octoprint_bedcheckai/utils.py#L35
> 
> ) -- it would be nice if your description was more upfront about this. Specifically, in the section "How does it work?" this aspect should be mentioned.
> You should also make sure it's mentioned in your privacy policy.
> 
> Or do you also offer the ability to self-host your models?

The OctoPrint listing directly mentions that it is run on the cloud (in the How does it work section): https://plugins.octoprint.org/plugins/bedcheckai/
See:
"
Bed Check AI uses a Deep Neural Network Segmentation model. The model determines which pixels within the image are associated with a print bed and then groups them together. The ML model is large so it is run on the cloud. This allows for you to utilize the tool on any piece of hardware, from anywhere in the world.
"

It is also mentioned in our Privacy Policy, which is listed on the OctoPrint plugin page, and on the plugin application within OctoPrint.

We do not offer a self-hosted version since the model is large and because it is proprietary.

**Comment by hn3000** [comment]
Thanks for the clarification.

Not sure why I didn't notice the "model is run in the cloud" part, but tbh, I don't find it that clear. It's buried in the middle of the paragraph and at no point do you explicitly mention that my images are uploaded to the cloud; I can see why you think that mentioning the model runs in the cloud should be clear enough, but it's certainly only implied, not explicitly mentioned. 

(Basically, this is a good example for the "don't make me think" principle -- while it may be 100% clear to anyone who knows enough about ML, the casual 3d printer user might just be spending 5s to read your description and will need it pointed out more clearly.)

**Comment by printpal-io** [comment]
Modified OctoPrint plugins page: https://github.com/OctoPrint/plugins.octoprint.org/pull/1236
